version: 2.1
orbs:
  node: circleci/node@5

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run: npm install -f
      - run: echo "Running tests and analysis..."

  deploy_and_notify:
    executor: node/default
    parameters:
      target_env:
        type: string
    steps:
      - checkout
      - run:
          name: Deploy Application
          command: echo "Deploying application to << parameters.target_env >> environment..."
      - run:
          name: Notify Deployment
          command: echo "Notification sent for deployment to << parameters.target_env >> environment..."

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy_and_notify:
          name: deploy_and_notify_develop
          requires:
            - build
          filters:
            branches:
              only: develop
          target_env: develop
      - deploy_and_notify:
          name: deploy_and_notify_main
          requires:
            - build
          filters:
            branches:
              only: main
          target_env: main
