version: 2.1
orbs:
  node: circleci/node@5

jobs:
  install-dependencies:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm install -f
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: echo "Dependencies installed successfully."

  code-analysis:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running code analysis..."

  clean-and-package:
    executor: node/default
    steps:
      - checkout
      - run: echo "Cleaning and packaging application..."

  deploy_and_notify_develop:
    executor: node/default
    parameters:
      target_env:
        type: string
    steps:
      - checkout
      - run: echo "Deploying application to << parameters.target_env >> environment..."
      - run: echo "Notification sent for deployment to << parameters.target_env >> environment..."

  verification-tests:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm run test -f

  functional-tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running functional tests..."

  load-tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running load tests..."

  monitoring-and-tracking:
    executor: node/default
    steps:
      - checkout
      - run: echo "Monitoring and tracking application..."

workflows:
  version: 2
  build-deploy-notify:
    jobs:
      - install-dependencies
      - code-analysis:
          requires:
            - install-dependencies
      - clean-and-package:
          requires:
            - code-analysis
      - deploy_and_notify_develop:
          requires:
            - clean-and-package
          filters:
            branches:
              only: develop
          target_env: develop
      - deploy_and_notify_main:
          requires:
            - clean-and-package
          filters:
            branches:
              only: main
          target_env: main
      - verification-tests:
          requires:
            - deploy_and_notify_develop
            - deploy_and_notify_main
      - functional-tests:
          requires:
            - deploy_and_notify_develop
            - deploy_and_notify_main
      - load-tests:
          requires:
            - deploy_and_notify_develop
            - deploy_and_notify_main
      - monitoring-and-tracking:
          requires:
            - deploy_and_notify_develop
            - deploy_and_notify_main
