version: 2.1
orbs:
  node: circleci/node@5

jobs:
  install-dependencies:
    executor: node/default
    steps:
      - checkout
      - run: npm install -f
      - run: echo "Dependencies installed successfully."

  code-analysis:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running code analysis..."

  clean-and-package:
    executor: node/default
    steps:
      - checkout
      - run: echo "Cleaning and packaging application..."

  deploy_and_notify:
    executor: node/default
    parameters:
      target_env:
        type: string
    steps:
      - checkout
      - run: echo "Deploying application to << parameters.target_env >> environment..."
      - run: echo "Notification sent for deployment to << parameters.target_env >> environment..."

  verification-tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running verification tests..."

  functional-tests:
  executor: node/default
  steps:
    - checkout
    - run: npm run test


  load-tests:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running load tests..."

  monitoring-and-tracking:
    executor: node/default
    steps:
      - checkout
      - run: echo "Monitoring and tracking application..."

workflows:
  version: 2
  build-deploy-notify:
    jobs:
      - install-dependencies
      - code-analysis:
          requires:
            - install-dependencies
      - clean-and-package:
          requires:
            - code-analysis
      - deploy_and_notify:
          name: deploy_and_notify_develop
          requires:
            - clean-and-package
          filters:
            branches:
              only: develop
          target_env: develop
      - deploy_and_notify:
          name: deploy_and_notify_main
          requires:
            - clean-and-package
          filters:
            branches:
              only: main
          target_env: main
      - verification-tests:
          requires:
            - deploy_and_notify_develop
            - deploy_and_notify_main
      - functional-tests:
          requires:
            - deploy_and_notify_develop
            - deploy_and_notify_main
      - load-tests:
          requires:
            - deploy_and_notify_develop
            - deploy_and_notify_main
      - monitoring-and-tracking:
          requires:
            - deploy_and_notify_develop
            - deploy_and_notify_main
