version: 2.1
orbs:
  node: circleci/node@5

jobs:
  # Job pour l'installation des dépendances
  install-dependencies:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install packages with -f
          command: npm install -f
      - run:
          name: Echo Dependencies Installed
          command: echo "Dependencies installed successfully."

  # Job pour l'analyse du code
  code-analysis:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Run Code Analysis
          command: echo "Running code analysis..."

  # Job pour le nettoyage et l'emballage de l'application
  clean-and-package:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Clean and Package Application
          command: echo "Cleaning and packaging application..."

  deploy_and_notify:
    executor: node/default
    parameters:
      target_env:
        type: string
    steps:
      - checkout
      - run:
          name: Deploy Application
          command: echo "Deploying application to << parameters.target_env >> environment..."
      - run:
          name: Notify Deployment
          command: echo "Notification sent for deployment to << parameters.target_env >> environment..."

workflows:
  version: 2
  build-deploy-notify:
    jobs:
      - install-dependencies
      - code-analysis:
          requires:
            - install-dependencies
      - clean-and-package:
          requires:
            - code-analysis
      - deploy_and_notify:
          name: deploy_and_notify_develop
          requires:
            - clean-and-package
          filters:
            branches:
              only: develop
          target_env: develop
      - deploy_and_notify:
          name: deploy_and_notify_main
          requires:
            - clean-and-package
          filters:
            branches:
              only: main
          target_env: main
